[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sudrabainiemakoni"
version = "0.01"
description = "Sudrabaino mākonu sinhronās novērošanas datu apstrādes rīki"
authors = [
    {name = "Juris Seņņikovs", email = "jsenniko@latnet.lv"}
]
dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "pyproj",
    "astropy",
    "exifread",
    "cameratransform==1.1",
    "pymap3d",
    "pykrige",
    "simplekml",
    "imageio",
    "pytz",
    "opencv_python"
]
requires-python = ">=3.7"

[project.optional-dependencies]
plotting = [
    "matplotlib",
    "tilemapbase"
]
utils = [
    "scikit-image",
    "Pillow"
]
geotiff = [
    "rasterio"
]
gui = [
    "photutils",
    "scikit-image",
    "PyQt5",
    "matplotlib",
    "tilemapbase",
    "platformdirs"
]

[project.scripts]
sudrabainie = "guihelpers.sudrabainie:main"

[tool.setuptools]
packages = ["sudrabainiemakoni", "sudrabainiemakoni.calibration", "sudrabainiemakoni.calibration.lens_distortions", "guihelpers"]
zip-safe = false

[tool.setuptools.package-data]
guihelpers = ["*.ui"]

